// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spfzjfxvdtacvpramgkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZnpqZnh2ZHRhY3ZwcmFtZ2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzczMzEsImV4cCI6MjA2MTUxMzMzMX0.Q70isDG8yxgk8zf0cedyNGe0zZ37cCgb8qR6D4xMAdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);